name: CI
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  ci:
    name: Format, lint, and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt -- --check
      - run: cargo clippy --all-features -- --deny warnings
      - run: cargo test --all-features

  features:
    name: Check feature combinations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - features: ""
          - features: "bytes"
          - features: "bitvec"
          - features: "bytes,bitvec"
          - features: "futures"
          - features: "futures,bytes"
          - features: "futures,bitvec"
          - features: "futures,bytes,bitvec"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - run: cargo clippy --features ${{ matrix.features }} --all-targets -- --deny warnings
